name: Application test/build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ClientApp/package-lock.json
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install backend dependencies
        run: dotnet restore
      - name: Install frontend dependencies
        working-directory: ./ClientApp
        run: npm ci
      - name: Test frontend
        working-directory: ./ClientApp
        run: npm run test
      - name: Build frontend
        working-directory: ./ClientApp
        run: npm run build
      - name: Build backend
        run: dotnet build --configuration Release --no-restore
      - name: Test backend
        run: dotnet test --no-restore --verbosity normal
      